# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  apigateway:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "Gateway/ApiGateWay/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "apigateway:dev"
    ports:
    - "127.0.0.1:57040:57100"
    - "127.0.0.1:57240:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\Gateway\\ApiGateWay:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  basket.api:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57041:57100"
    - "127.0.0.1:57241:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\Services\\Basket\\\
      Basket.API:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57042:57100"
    - "127.0.0.1:57242:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\Services\\Catalog\\\
      Catalog.API:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  promotion.api:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "Services/Promotion/Promotion.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "promotionapi:dev"
    ports:
    - "127.0.0.1:57043:57100"
    - "127.0.0.1:57243:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\Services\\Promotion\\\
      Promotion.API:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  promotion.grpc:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "Services/Promotion/Promotion.GRPC/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "promotiongrpc:dev"
    ports:
    - "127.0.0.1:57044:57100"
    - "127.0.0.1:57244:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\Services\\Promotion\\\
      Promotion.GRPC:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  purchasing.api:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "Services/Purchasing/Purchasing.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "purchasingapi:dev"
    ports:
    - "127.0.0.1:57045:57100"
    - "127.0.0.1:57245:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\Services\\Purchasing\\\
      Purchasing.API:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  shoep.management:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "WebApp/Shoep.Management/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Shoep.Management.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "shoepmanagement:dev"
    ports:
    - "127.0.0.1:57046:57100"
    - "127.0.0.1:57246:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\WebApp\\Shoep.Management:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  shoep.shop:
    build:
      context: "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src"
      dockerfile: "WebApp/Shoep.Shop/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Shoep.Shop.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "shoepshop:dev"
    ports:
    - "127.0.0.1:57047:57100"
    - "127.0.0.1:57247:57300"
    volumes:
    - "C:\\Users\\daxng\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src\\WebApp\\Shoep.Shop:/app:rw"
    - "D:\\FULearning\\fall24\\2_PRN231\\2_PRN231\\eShoep\\src:/src:rw"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\daxng\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_10_14_10_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
