// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotion.API.Data;

#nullable disable

namespace Promotion.API.Migrations
{
    [DbContext(typeof(PromotionContext))]
    [Migration("20241025112941_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Promotion.API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150,
                            CouponType = 1,
                            Description = "IPhone Promotion",
                            ProductId = new Guid("5334c996-8457-4cf0-815c-ed2b77c4ff61")
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100,
                            CouponType = 0,
                            Description = "Samsung Promotion",
                            ProductId = new Guid("5334c996-8457-4cf0-815c-ed2b77c4ff61")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
