version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  purchasingdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  promotion.grpc:
    image: ${DOCKER_REGISTRY-}promotiongrpc
    build:
      context: .
      dockerfile: Services/Promotion/Promotion.Grpc/Dockerfile

  purchasing.api:
    image: ${DOCKER_REGISTRY-}purchasingapi
    build:
      context: .
      dockerfile: Services/Purchasing/Purchasing.API/Dockerfile
  
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateway/ApiGateWay/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket: