version: '3.4'

services:
  catalogdb:
    image: postgres

  promotiondb:
    image: postgres

  basketdb:
    image: postgres

  identitydb:
    image: postgres

  distributedcache:
    image: redis

  purchasingdb:
    image: postgres

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  promotion.api:
    image: ${DOCKER_REGISTRY-}promotionapi
    build:
      context: .
      dockerfile: Services/Promotion/Promotion.API/Dockerfile

  promotion.grpc:
    image: ${DOCKER_REGISTRY-}promotiongrpc
    build:
      context: .
      dockerfile: Services/Promotion/Promotion.GRPC/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  purchasing.api:
    image: ${DOCKER_REGISTRY-}purchasingapi
    build:
      context: .
      dockerfile: Services/Purchasing/Purchasing.API/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateway/ApiGateWay/Dockerfile

  shoep.shop:
    image: ${DOCKER_REGISTRY-}shoepshop
    build:
      context: .
      dockerfile: WebApp/Shoep.Shop/Dockerfile

  shoep.management:
    image: ${DOCKER_REGISTRY-}shoepmanagement
    build:
      context: .
      dockerfile: WebApp/Shoep.Management/Dockerfile

volumes:
  postgres_catalog:
  postgres_promotion:
  postgres_basket:
  postgres_identity:
  postgres_purchasing:





