version: '3.4'

services:
  catalogdb:
    image: postgres

  discountdb:
    image: postgres

  basketdb:
    image: postgres

  identitydb:
    image: postgres

  distributedcache:
    image: redis

  purchasingdb:
    image: postgres

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

#  promotion.api:
#    image: ${DOCKER_REGISTRY-}promotionapi
#    build:
#      context: .
#      dockerfile: Services/Promotion/Promotion.API/Dockerfile

  purchasing.api:
    image: ${DOCKER_REGISTRY-}purchasingapi
    build:
      context: .
      dockerfile: Services/Purchasing/Purchasing.API/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateway/ApiGateWay/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  shoep.shop:
    image: ${DOCKER_REGISTRY-}shoepshop
    build:
      context: .
      dockerfile: WebApp/Shoep.Shop/Dockerfile

volumes:
  postgres_catalog:
  postgres_discount:
  postgres_basket:
  postgres_identity:
  postgres_purchasing:



